name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  backend-build-and-test:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./backend

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25.0'
        cache-dependency-path: backend/go.sum

    - name: Install dependencies
      run: go mod download

    - name: Build
      run: go build -v ./...

    - name: Run Tests
      run: go test -v ./...

  frontend-build-and-lint:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./frontend

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Install dependencies
      run: npm ci

    - name: Lint
      run: npm run lint

    - name: Build
      run: npm run build
